# N-CASA Manual Test - Fortinet
config system global
    set hostname "N-CASA-FORTIGATE"
end

config system interface
    edit "wan"
        set ip 192.0.2.30 255.255.255.252
        set allowaccess ping https ssh
    next
    edit "lan"
        set ip 198.51.100.30 255.255.255.0
        set allowaccess ping https ssh
    next
end

config system ntp
    set ntpsync enable
    config ntpserver
        edit 1
            set server "10.10.10.20"
        next
    end
end

config log syslogd setting
    set status enable
    set server "10.10.10.10"
end

config firewall policy
    edit 1
        set name "DEFAULT-DENY"
        set srcintf "wan"
        set dstintf "lan"
        set srcaddr "all"
        set dstaddr "all"
        set action deny
        set schedule "always"
        set service "ALL"
    next
end
